version: '3.5'
services:
  react-app:
    container_name: 'reactfrontend'
    image: react-app
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - mern-app
    volumes:
      - ./client/src:/app/client/src
  api-server:
    container_name: 'nodebackend'
    image: api-server
    ports:
      - '5000:5000'
    networks:
      - mern-app
    volumes:
      - ./server:/app/server
    environment:
      PORT: 5000
networks:
  mern-app:
    driver: bridge
