version: '3.5'
services:
  react-app:
    container_name: 'reactfrontend'
    build:
      context: ./client
      dockerfile: dockerfile.react
    tty: true
    image: react-app
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - mern-app
    volumes:
      - ./client:/app/client
  api-server:
    container_name: 'nodebackend'
    build:
      context: ./server
      dockerfile: dockerfile.node
    image: api-server
    ports:
      - '5000:5000'
    networks:
      - mern-app
    volumes:
      - ./server/configs:/app/server/configs
      - ./server/controllers:/app/server/controllers
      - ./server/middleware:/app/server/middleware
      - ./server/models:/app/server/models
      - ./server/routers:/app/server/routers
      - ./server/app.js:/app/server/app.js
    env_file: ./server/.env
    #environment:
    # - PORT= ${PORT}
    # - ACCESS_TOKEN_SECRET=$${ACCESS_TOKEN_SECRET}

networks:
  mern-app:
    driver: bridge
